var express = require('express');
var router = express.Router();
var checkAuth = require('../validate_func/CheckAuth');
var adminCtrl = require('../controllers/adminCtrl');
router.get('/admin', checkAuth.checkAuthenticated, adminCtrl.getAdminPage);
router.get('/admin/manageBlog', checkAuth.checkAuthenticated, checkAuth.isEditor, adminCtrl.getAdminManageBlog);
router.get('/admin/addBlog', checkAuth.checkAuthenticated, checkAuth.isEditor, adminCtrl.getAdminAddBlog);
router.get('/admin/editBlog/:blogslug', checkAuth.checkAuthenticated, checkAuth.isEditor, adminCtrl.getAdminEditBlog);
router.get('/admin/deleteBlog/:blogslug', checkAuth.checkAuthenticated, checkAuth.isEditor, adminCtrl.getAdminDeleteBlog);
router.post('/admin/editBlog/:blogslug', checkAuth.checkAuthenticated, checkAuth.isEditor, adminCtrl.postAdminEditBlog);
router.post('/admin/addBlog', checkAuth.checkAuthenticated, checkAuth.isEditor, adminCtrl.postAdminAddBlog);
module.exports = router;